name: Testing conditions
on:
  push:
    branches:
      - main
      - dev
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  USUAL_FILE: '.env.development'
  TEST_FILE: '.env.development.edge'
  FILE_TO_USE: ${{ github.ref == 'refs/heads/main' && '.env.development' || '.env.development.edge' }} 
  NAMESPACE: 'service-something'
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: First job that tests conditions
        env:
          TEST_VARIABLE: ${{ contains(fromJson('["dev"]'), env.BRANCH_NAME) && '.env.development' || '.env.development.edge' }}
        run: |
          echo "TEST_VARIABLE: $TEST_VARIABLE"
      - name: Using ternary condition
        env:
          FILE_TO_READ: ${{ github.ref == 'refs/heads/main' && env.NAMESPACE || join(toJson('[env.NAMESPACE, ".test"]'),'+') }}
        run: |
          echo File to read is $FILE_TO_READ
      